### ISSUE TITLE
Minification problem 

### ISSUE THREAD

**Issue by leolara** [auth0/angular-jwt#10]
Not sure if it is about this project or $httpProvider.

When I do `$httpProvider.interceptors.push('jwtInterceptor');`

I got the error Error: [$injector:unpr] Unknown provider: aProvider <- a 

Only when I am doing minification. If I comment out that line then I do not get that error.

**Comment by umar2code** [comment]
should initialize authProvider.init()

**Comment by deviantony** [comment]
For some reasons I'm still having minifications issues...

Also, I cannot use the code specified in the docs: 

```
jwtOptionsProvider({
  tokenGetter: ['store', '$http', function(store, $http) {
    ...
  }]
});
``` 

When I'm using this I get:

```
jwtOptionsProvider is not a function
```
