### ISSUE TITLE
Injection in blok config

### ISSUE THREAD

**Issue by nahuelramos** [auth0/angular-jwt#100]
hello my problem is that I have the url in a constant block which can not injected into the config block someone could give me an example of how to fix it.

knowing that in the config block I can not inject constant, I do not know on replace my constant in a provider and how

**Comment by chenkie** [comment]
Can you provide a bit more detail and some of your code? :)

**Comment by nahuelramos** [comment]
Thanks for your answer, i have a problem with dependency injection, but I solved it.
