### ISSUE TITLE
White list a whole domain or domain regex

### ISSUE THREAD

**Issue by carlosfunk** [auth0/angular-jwt#109]
Hi,

I have a use case where sub domains are created dynamically so I'm not able to whitelist them beforehand.  Would it be possible to whitelist an entire domain or provide a regex to whitelist?

e.g something like 

`whiteListedDomains: ['.example.com']`
or 
`whiteListDomainRegex: '(\w+\.)?example\.com$'`

**Comment by chenkie** [comment]
That's definitely something we can look at doing. I think the easiest approach would be to whitelist a domain so that any subdomain applies.

**Comment by fvilers** [comment]
I would need this feature too. On my projects, for each PR made by the team, a review app is deployed on Heroku. It's domain looks like `my-app-pr-123.herokuapp.com`. Even if the risk is pretty small, I'd like to not white list `herokuapp.com` but rather `myapp(-pr-\d+)?\.herokuapp\.com$`

**Comment by dusty** [comment]
This may be helpful but may not be doable for many cases.  I was originally looking to use a regex match for something similar to *.herokuapp.com, but decided on a different strategy.

During bootstrap, I am making an http request to my backend to get some configuration variables.  I'll set that as a const and then inject it into my jwt config.  Inside that const is the API URL that I will be using for this client.  I happen to know this URL beforehand, some might not.

```
function jwtInterceptorConfig ($httpProvider, jwtOptionsProvider, APP) {
    // Set whiteListedDomains based on APP.apiURL
    var whiteListedDomains = []
    var parser = document.createElement('a')
    parser.href = APP.apiURL
    if (parser.hostname) {
      whiteListedDomains.push(parser.hostname)
    }
    jwtOptionsProvider.config({
      whiteListedDomains: whiteListedDomains,
      ...
```

**Comment by eskatos** [comment]
In one of my use cases, having a function providing the "white listed" hosts to `angular-jwt` would be the only viable option as that "list" is dynamic.

**Comment by chenkie** [comment]
Implemented in 0.1.9

**Comment by ryanwalls** [comment]
@dusty Mind sharing how you're doing an http call in your bootstrap?  I keep running into the problem of making sure the http call happens before the `jwtOptionsProvider` is configured.

**Comment by dusty** [comment]
Sure.  This is how I bootstrap angular.

```
function bootstrap() {
    var $injector = angular.injector(['ng'])
    var $http = $injector.get('$http')
    $http
      .get('/app/info')
      .then(function(response) {
        var app = JSON.parse(response.data)
        angular
          .module(moduleName)
          .constant('APP', app)
          .config(locationConfig)
          .config(routeConfig)
          .config(httpSyncConfig)
          .config(deleteHttpConfig)
          .config(xmlHttpInterceptorConfig)
          .config(authInterceptorConfig)
          .config(jwtInterceptorConfig)
        angular.element(document.getElementById(moduleId)).ready(function() {
          angular.bootstrap(document, [moduleName])
        })
      })
      .catch(function(error) {
        console.log('error', error)
      })
  }

  bootstrap()
```
