### ISSUE TITLE
verifyRoute not $Injector safe

### ISSUE THREAD

**Issue by mgoodings** [auth0/angular-jwt#113]
The following example code from the README will fail when verifyRoute in authManager.js is called, an exception saying the following is triggered: config.unauthenticatedRedirector is not a function.

```
angular
  .module('app', ['angular-jwt'])
  .config(function Config($httpProvider, jwtOptionsProvider) {
    jwtOptionsProvider.config({
      unauthenticatedRedirector: ['$state', function($state) {
        $state.go('app.login');
      }]
    });
  });
```

Solution:

https://github.com/auth0/angular-jwt/blob/master/src/angularJwt/services/authManager.js#L63

should match the pattern followed here:

https://github.com/auth0/angular-jwt/blob/master/src/angularJwt/services/authManager.js#L43

**Comment by chenkie** [comment]
Fixed in 0.1.7
