### ISSUE TITLE
tokenHasExpired is not called

### ISSUE THREAD

**Issue by northkode** [auth0/angular-jwt#117]
in my main app controller i have 
```$rootScope.$on('tokenHasExpired', function() {
            alert('Your session has expired!');
        });```

but it is never called even tho the jwtHelper does say that the token is expired

**Comment by chenkie** [comment]
When are you expecting the call to be made? It should be firing on page refresh.

**Comment by northkode** [comment]
I looked through the code and realized the tokenGetter needs to return the token always vs if expired i was returning null.. that stopped the tokenHasExpired event from running.. 

but I'm still not getting the authentication redirect even tho now i get TokenHasExpired event

```.run(function(authManager) {
		authManager.checkAuthOnRefresh();
		authManager.redirectWhenUnauthenticated();
	});
```

and then

```
jwtOptionsProvider.config({
		tokenGetter : function() {
	        return localStorage.getItem('token');
		},
		unauthenticatedRedirectPath: function() {
			console.log("we are not authenticated, this is not running");
		},
        whiteListedDomains: ['localhost',urlResolve(API_URL).hostname.toLowerCase()]
    });
```

**Comment by chenkie** [comment]
It looks like that should be `unauthenticatedRedirector` instead of `unauthenticatedRedirectPath`.

**Comment by northkode** [comment]
got everything working.  thanks!
