### ISSUE TITLE
bower angular-jwt#~0.0.6       ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/auth0/angular-jwt.git", exit code of #128 fatal: unable to access 'https://github.com/auth0/angular-jwt.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

### ISSUE THREAD

**Issue by xhz-bza** [auth0/angular-jwt#118]
Why？

**Comment by chenkie** [comment]
Is this still happening? I wasn't able to reproduce it. Do you have the latest version of bower installed?

**Comment by xhz-bza** [comment]
bower 1.7.9

**Comment by xhz-bza** [comment]
Now what do I do，It's very urgent.I want to build the shipyard.

**Comment by chenkie** [comment]
In all likelihood this is a network issue. Here's an SO thread with some tips: https://stackoverflow.com/questions/21544803/git-bower-errors-exit-code-128-failed-connect
