### ISSUE TITLE
Problem adding token to request header

### ISSUE THREAD

**Issue by sangameshb15** [auth0/angular-jwt#121]
Hello,

I am using jwt token for authorization and facing issue adding token to request header.

My angularjs site running on localhost:3000 and I  have whitelisted the localhost domain.

When made request to api running on localhost with different port number i.e., localhost:8080/api/demoapi, the token is not getting added to request header.

For trial purpose if I change the port number of api to 3000,
hence changing api port same as angularjs site, it works.

How can i resolve this issue?

**Comment by chenkie** [comment]
You've tried doing this?

`whiteListedDomains: ['localhost']`?

**Comment by sangameshb15** [comment]
I tried whiteListedDomains. But no luck

**Comment by chenkie** [comment]
It hard to tell what could be causing this. 

Does it happen with any kind of `$http` request?

**Comment by sangameshb15** [comment]
Thanks it worked
