### ISSUE TITLE
Token is not being sent in header for subsequent POST requests

### ISSUE THREAD

**Issue by rajkumar-qsg** [auth0/angular-jwt#122]
Hi,
Token is not being sent or added in header for subsequent  request if request is POST, but token is adding to header if request is GET method, for POST method its not being added to header. Is there any changes i need to do to work it for post method also?

**Comment by chenkie** [comment]
there shouldn't be anything different. can you post your configuration?

**Comment by rajkumar-qsg** [comment]
![get](https://cloud.githubusercontent.com/assets/15885912/20236231/5345690c-a8d4-11e6-9403-d2c6a5124daf.png)
![post](https://cloud.githubusercontent.com/assets/15885912/20236232/5c295376-a8d4-11e6-9cf7-20d61cb4b486.png)

Hi,

I have attached screen shots of request and response i am getting for GET and POST methods. Please find the attachments.

Thank you.

**Comment by rajkumar-qsg** [comment]
Hi,

I found out that its working for http call but its not working for ajax call, is there any settings need to be changed for ajax call?

**Comment by chenkie** [comment]
Can you give an example of the code you're using when it doesn't get attached? Just for clarification, it gets attached to any of the calls made by the `$http` service.
