### ISSUE TITLE
Token is being sent in header for https://www.example.com but not for https://example.com

### ISSUE THREAD

**Issue by sangameshb15** [auth0/angular-jwt#123]
I have whitelisted the domain.

 whiteListedDomains: ['localhost', 'www.example.com']

When accessed the site with www in the url Ex: https://www.example.com, auth token gets added in request header successfully. But its wont work for the url https://example.com

**Comment by chenkie** [comment]
what if you whitelist both? or just like this: `whiteListedDomains: ['example.com']`
