### ISSUE TITLE
Prefix services and events with a namespace

### ISSUE THREAD

**Issue by ptitgraig** [auth0/angular-jwt#130]
Hello.

Thanks for your great work !

I suggest some refactoring that could greatly improve code redability.

Unlike ui-bootstrap which prefixes services with `$uib` (like $uibModal), prefix services with a trigram. I suggest `$jwt`.
I especially think about the authManager which at first glance don't know where it comes from when we maintain an application created by someone else.

* `authManager`: `$jwtAuthManager`

Events could become:
* `tokenHasExpired`: `$jwt:tokenHasExpired` or `jwt:tokenHasExpired`
* `unauthenticated`:  `$jwt:unauthenticated` or `jwt:unauthenticated`

Regards

**Comment by chenkie** [comment]
Thanks for your feedback :)

I'll be evaluating a v1 major release soon, at which point I think something along these lines could be included.
