### ISSUE TITLE
Token not sent -- Probably something in the whiteListedDomains

### ISSUE THREAD

**Issue by rolandpeelen** [auth0/angular-jwt#131]
I have some issues here as well. I'm deploying to Heroku, tokens get sent in fine when using```localhost``` or ```127.0.0.1``` but when using ```app.herokuapp.com``` the token doesn't get sent anymore (wether that's on heroku or on local, I can't make calls to the actual api, just dev api) Any clue?

**Comment by chenkie** [comment]
What do you have as your `whiteListedDomains`?

**Comment by rolandpeelen** [comment]
```
jwtOptionsProvider.config({ 
      whiteListedDomains: [
        'localhost', 
        '127.0.0.1',
        '****.herokuapp.com'
      ]});
```

If I remove the localhost from the list, the headers aren't sent in localhost, so the config does what it should, but apparently not for the ```***.herokuapp.com```

**Comment by chenkie** [comment]
do you have `***` in as your Heroku subdomain or is that just for display purposes here? There isn't support for wildcard domains yet if that's what you're trying to do.

**Comment by rolandpeelen** [comment]
Just display purposes :) --> It's formatted as 'app-admin-staging.herokuapp.com' with app being the app name

**Comment by chenkie** [comment]
Out of curiosity, does it work if you have only the heroku domain in the array? and not `localhost` and `127.0.0.1`?

**Comment by rolandpeelen** [comment]
Allright, I managed to find the problem, did not have anything to do with the JWT options! Thanks for the quick replies @chenkie

**Comment by chenkie** [comment]
np, glad you found it!
