### ISSUE TITLE
isTokenExpired validation using local time 

### ISSUE THREAD

**Issue by deviantony** [auth0/angular-jwt#133]
Hi @chenkie,

From what I can read in the code of this library, it looks like it's using the local time of the user to check if the token is expired. It does a comparison of the date of the token (in UTC, using `d.setUTCSeconds()` to set token expiration date) against the current time (in the user local timezone, using `new Date()` to get current time): https://github.com/auth0/angular-jwt/blob/45ab6b4d9c1be87eb6f5654c844d2895529acd2b/src/angularJwt/services/jwt.js#L54

I'm wondering if this could not raise timezone conflicts issues? I've setup an application where I'm using JWT with short expiration time (**8 hours**) and I've got people reporting weird issues where the token expiration time they got after login is already expired (token is generated ~24h in the past):

> For example, it is currently Tue Dec 12 2016 00:08 GMT+0100 (CET).
When checking the JWT expire date (using the jwtHelper that is used to validate it) gives me:
getTokenExpirationDate: Mon Dec 12 2016 03:58:02 GMT+0100 (CET)

Note that the token is generated using UTC time on the backend of my application.

**Comment by thomasmktong** [comment]
I am facing a similar problem. I think we can use the `offsetSeconds` param in `isTokenExpired` function to solve this on our own.

Note that if you use function `authManager.checkAuthOnRefresh()` and event `tokenHasExpired`, you need to implement the logic yourself, it has no `offsetSeconds` to configure. But I think it should be added for consistency.

**Comment by Mario-Eis** [comment]
We are facing a similar issue. If the client has a wrong date and/or time set, there will be a infinite refresh loop. Because every received token is invalid from the clients point of view.

**Comment by blckshrk** [comment]
I'm facing the same issue as @Mario-Eis. Did you have a workaround for different timezone like us ?

**Comment by jmls** [comment]
oh, dammit, just got bitten by this as well - server is creating a expiry of 30 mins from now (utc), browser is running bst, so it's 1 hour ahead. jwt "expires" as soon as the client gets the jwt ...

**Comment by korengal** [comment]
any solution for this issue?
