### ISSUE TITLE
Update RxJS dependency to 5.0.x

### ISSUE THREAD

**Issue by the-ult** [auth0/angular-jwt#134]
The new angular-cli and angular 2.3.x requires rxjs 5.0.1
angular-jwt still requires rxjs beta-12

**Comment by chenkie** [comment]
Sounds like this is for angular2-jwt :)

There's actually a PR in flight there right now: https://github.com/auth0/angular2-jwt/pull/253

**Comment by the-ult** [comment]
Sorry.. you're right.. forgot the `2` in the url.. :-S
