### ISSUE TITLE
AuthHttp overwrite windows authentication or conflict?

### ISSUE THREAD

**Issue by sk29110** [auth0/angular-jwt#139]
I started implement token authentication on my application and use authHttp to call api but every time I make request to get data from the asp.net server side the windows authentication dialog pops up although it's been authenticated already. It doesn't do if I just use angular/http. I am not sure why this is happening.

**Comment by gabrieleciech** [comment]
This happens because the authentication token is added to the header of the http request automatically by the jwtInterceptor. If you do not use angular $http you need to add manually the Authorization header to the request.

**Comment by chenkie** [comment]
@sk29110 it sounds like you may be using [angular2-jwt](https://github.com/auth0/angular2-jwt). If so, can you close this issue and post it there?
