### ISSUE TITLE
Refresh Token example question

### ISSUE THREAD

**Issue by kokujin** [auth0/angular-jwt#14]
In the Refresh Token code example, there is a line that shows how to retrieve the new token for the refresh:

```
var refreshToken = localStorage.getItem('refresh_token');
```
1. At what point or where is this local storage value set?
2. Is there a reason why a new token is generated instead of just sending the token back with a new expiry date?

Thanks

**Comment by monomichael** [comment]
@mgonto Why don't we just use `id_token` to validate the user and return a refreshed token? Even if a token is expired, we are still able to decode and validate the token.

**Comment by swinston1000** [comment]
@kokujin 
I am looking for a  Refresh Token code example where did you find it?
