### ISSUE TITLE
Authorization: Bearer with/without quotes?

### ISSUE THREAD

**Issue by Fossil01** [auth0/angular-jwt#141]
My API expects the header like so:

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9blablablablabla

But Angular-JWT sends the request with the token itself encapsulated in quotes:

Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9blablablablabla"

This makes the request fail. Any idea how to fix this? According to JWT.io the format should be:
```
Authorization: Bearer <token>
```

[EDIT] I just realized the quotes come from the way the token is stored in local storage using angular-storage.

**Comment by giathinh910** [comment]
Hi @Fossil01. Have you found out the way to remove quote when storing using angular-storage?

**Comment by Fossil01** [comment]
No, but I remove the quotes on every HTTP request:

```javascript
app.config(function Config($httpProvider, jwtOptionsProvider, $locationProvider) {
	jwtOptionsProvider.config({
		tokenGetter: ['options', function(options) {
			// Skip authentication for these URL's
			if (options.url.substr(options.url.length - 5) == '.html' || options.url == API + '/login') {
				return null;
			}
			let token = localStorage.getItem('jwt')
			if (token) {
				token = token.replace(/^"(.*)"$/, '$1'); // Remove quotes from token start/end. This is a temp fix?!
				return token;
			}
		}],
		whiteListedDomains: ['SOMEWEBSITE.COM', 'localhost']
	});
	$httpProvider.interceptors.push('jwtInterceptor');
	// $locationProvider.html5Mode(true);
});
```

**Comment by giathinh910** [comment]
Thanks @Fossil01, I also have to do like this. Don't know why the author add quote to storage value.

**Comment by akalightowl** [comment]
Maybe author store all data in one JSON value in one key? I see several code part with this in different tutorial.

**Comment by saurabh-dev-work** [comment]
Hi @Fossil01,
This issue is not because of Angular-JWT. Its just because you set your token in local storage with string or you are getting it in string/with quotes:
Do not use JSON.stringify() Just do this:

**localStorage.setItem('token', data.userToken);
and then logout and re-login to unset and reset the token.**

**Comment by vaail** [comment]
@Fossil01 @giathinh910 @akalightowl 
Use store.get('jwt') in tokenGetter.

**Comment by fromage9747** [comment]
@saurabhvedwal thank you!

**Comment by trancephorm** [comment]
I have this same problem but I didn't yet find out how to store JWT in LocalStorage without quotes, so I have to use ugly slicing when I'm sending JWT as Bearer token. Anybody help me?

**Comment by fromage9747** [comment]
> I have this same problem but I didn't yet find out how to store JWT in LocalStorage without quotes, so I have to use ugly slicing when I'm sending JWT as Bearer token. Anybody help me?

Post your issue on Stackoverflow, link it here and I will help you.

**Comment by trancephorm** [comment]
Here it is: https://stackoverflow.com/questions/70313399/how-to-store-jwt-in-localstorage-but-not-as-a-string
