### ISSUE TITLE
checkAuthOnRefresh: promise or event?

### ISSUE THREAD

**Issue by guillaumegarcia13** [auth0/angular-jwt#144]
Is there a way to hook on the checkAuthOnRefresh()? 
For instance, using a promise (or by emitting an event) when the authentication is done (or failed) so that actions can be triggered upon successful logon.

**Comment by chenkie** [comment]
There's nothing out of the box unfortunately. PRs are welcome though!

**Comment by guillaumegarcia13** [comment]
Something like this seems to do the trick
```
authManager.authenticate = (function(core) {
    function extended() {
        core();
        $rootScope.$broadcast('authenticationIsDone');
    }

    return extended;
})(authManager.authenticate);
```

**Comment by guillaumegarcia13** [comment]
Eventually, I ended up using a resolve in angular ui-router to refresh the internal state from the JWT that I stored in localStorage.
