### ISSUE TITLE
Confusing method called "isAuthenticated()"

### ISSUE THREAD

**Issue by motin** [auth0/angular-jwt#145]
This method looks like a getter for the isAuthenticated property, which btw is set on $rootScope (also confusing), but it is not. 

Maybe it should be renamed idTokenIsNotExpired() or similar?

**Comment by chenkie** [comment]
It's actually doing a direct check on the token for whether it is expired. Idea being you can do something like:

```html
<div class="profile" ng-if="vm.authManager.isAuthenticated()">...</div>
```

As a public method I think it's more understandable being called `isAuthenticated`, no?

**Comment by motin** [comment]
In that case simply using vm.authManager.isAuthenticated and not even using $rootScope is cleaner as proposed in https://github.com/auth0/angular-jwt/issues/90

Internally, the "isAuthenticated()" method can then be properly renamed to what it actually does and used in the process of setting authManager.isAuthenticated to true or false.

**Comment by chenkie** [comment]
I'm not sure I follow. The `isAuthenticated` method doesn't set anything but rather returns a boolean. Are you talking about `authenticate`?

**Comment by motin** [comment]
https://github.com/auth0/angular-jwt/search?utf8=%E2%9C%93&q=isAuthenticated&type=
The same phrase is being used for different purposes. 

If there is a variable inside a class and a method with the same name, it is often assumed to return the value of that variable, but not here. 

Proposal: Stop using $rootScope.isAuthenticated (as suggested in #90 ) and the confusion goes away as well. 

The usage will then be, from views:
```
<div class="profile" ng-if="vm.authManager.isAuthenticated">...</div>
```

Instead of the cryptic auto-magic variant that only works in views where $rootScope is inherited:
```
<div class="profile" ng-if="isAuthenticated">...</div>
```
