### ISSUE TITLE
[BUG] Requesting multiple times the refresh token

### ISSUE THREAD

**Issue by pabloleone** [auth0/angular-jwt#148]
If a user token is expired, the system uses the tokenGetter factory method to retrieve a new token, the problem is when multiple calls separated by milliseconds are performed. The backend sends the refreshed token only to the first call, the rest of the call receive a 401 code and there's a change the backend blacklists the token because it was used multiple times to authenticate after it's expired.

How can we stop calls while waiting for the token to get refreshed?

**Comment by MasterThinh** [comment]
this issue is same me

**Comment by jonathan-bird** [comment]
@pabloleone How'd you solve this in your token interceptor?
