### ISSUE TITLE
Missing Logout Mechanism

### ISSUE THREAD

**Issue by RL-shashikantmaharshi** [auth0/angular-jwt#149]
JWT logout option seems to be missing in this, could you please introduce it here.

I tried some guess work by removing local storage items associated with JWT authentication e.g. token, exp, user. But somehow they gets refreshed in subsequent requests through backend because of this unable to manage logout functionality in JWT.

In case if I am missing here any step then please guide me OR if you guys are currently implementing JWT Logout feature then please let me know when may I expect next release with it.

**Comment by chenkie** [comment]
Since JWT is a stateless authentication mechanism, logging the user out is simply a matter of removing any reference to their token. If you have saved their token in local storage, then it is necessary to remove it from there, but it also may be necessary to deal with any kind of caching of the token that may have happened. Do you have some kind of header caching happening for your `$http` requests?

**Comment by RL-shashikantmaharshi** [comment]
Thanks Ryan for your quick response & highlighting hotspot of this issue.

After spending quality time in debugging our SSO implementation layer found
it was the main culprit that was passing new token back in case of
unauthorized state which in turn stored back to local storage after wiping
it out in subsequent request.

**Comment by passatgt** [comment]
You also need to set $rootScope.isAuthenticated to false.

**Comment by dipesious** [comment]
**but friend, 
how am i suppose to do it?
i'm stuck with this...**

`
import { Injectable } from '@angular/core';
import { Http, Headers, RequestOptions } from '@angular/http';
import 'rxjs/add/operator/map';
//import { tokenNotExpired } from 'angular2-jwt';
import { JwtHelperService } from '@auth0/angular-jwt';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root'
})
export class AuthService {

  // domain = ""; // Production
  domain = environment.domain;
  authToken;
  user;
  options;

  constructor(
    private http: Http,
    public jwtHelper: JwtHelperService
  ) { }

  // Function to create headers, add token, to be used in HTTP requests
  createAuthenticationHeaders() {
    this.loadToken(); // Get token so it can be attached to headers
    // Headers configuration options
    this.options = new RequestOptions({
      headers: new Headers({
        'Content-Type': 'application/json', // Format set to JSON
        'authorization': this.authToken // Attach token
      })
    });
  }

  // Function to get token from client local storage
  loadToken() {
    this.authToken = localStorage.getItem('token');; // Get token and asssign to variable to be used elsewhere
  }

  // Function to login user
  login(user) {
    return this.http.post(this.domain + 'authentication/login', user).map(res => res.json());
  }

  // Function to store user's data in client local storage
  storeUserData(token, user) {
    localStorage.setItem('token', token); // Set token in local storage
    localStorage.setItem('user', JSON.stringify(user)); // Set user in local storage as string
    this.authToken = token; // Assign token to be used elsewhere
    this.user = user; // Set user to be used elsewhere
  }
  
  // Function to logout
  logout() {
    this.authToken = null; // Set token to null
    this.user = null; // Set user to null
    localStorage.clear(); // Clear local storage
  }

  // Function to check if user is logged in
  loggedIn() {
    return this.jwtHelper.isTokenExpired()
    //return tokenNotExpired();
    //return false;
    //this.jwtHelper.isTokenExpired()
  }

}
`
