### ISSUE TITLE
Question - Using angular-jwt with Restangular.

### ISSUE THREAD

**Issue by cerdman** [auth0/angular-jwt#15]
Something tells me I should be able to get some help owing to the creator of this repo.

I would like to switch over from our painful token/csrf/cookie based auth system to JWTs... We are using Restangular in production, and I have a number of factories providing Restangular instances. Would the setup be any different? I.e. need to use a global `$http` interceptor as shown vs. an interceptor for a particular `Restangular.withConfig()` ?

If I can get my head around it I'd be happy to contribute back to the docs with an example. Thanks.

**Comment by KidA001** [comment]
@cerdman - classic ask and answer get a response and say nothing.

@mgonto - Thank you, this was helpful. Switching over to JWT myself and using restangular.

**Comment by simonepri** [comment]
Sorry if i'm updating an old issue.
@mgonto 
I have not been able to make "angular-jwt" work with the jwtInterceptor as you suggested:

`$httpProvider.interceptors.push('jwtInterceptor');`

Regular $http requests have the 'Authorization' header correctly setted, but this is not true for the ones made by Restangular. (Maybe Restangular reset the request headers with its own defaults)
But i've figured out that Restangular provides its own interceptor, so i was able to set the 'Authorization' header manually by using this snippet:
```
RestangularProvider.setFullRequestInterceptor(function(element, operation, route, url, headers, params, httpConfig) {
  var jwt = $window.localStorage.getItem('jwt');
  if(jwt && !angular.isString(headers.Authorization)) {
    headers.Authorization = 'Bearer ' + jwt;
  }
  return {
    element: element,
    params: params,
    headers: headers,
    httpConfig: httpConfig
  };
});
```
It's not an elegant solution, but it works.
Hope it may be helpful for someone.

**Comment by AndrewJHart** [comment]
Can confirm that Restangular is not respecting the http interceptor(s) as mentioned by @simonepri - Does anyone know why? I would be happy to contribute a fix if that sounds good. 

Thanks,

**Comment by bampakoa** [comment]
I can also confirm that is not working in 0.1.9 version.

**Comment by wolfen351** [comment]
I think this could be abused to harvest Jwt tokens - if you can convince restangular to call to another domain, it will happily send the token without checking the whitelist
