### ISSUE TITLE
skipAuthorization for the login state

### ISSUE THREAD

**Issue by enricop89** [auth0/angular-jwt#151]
Hi all,

I am some issues configuring my app. Let's say I have a login state:

```
.state('app.login', {
            url: '/login'
})
```

I want to Skip authorization for this state (or Url) but I don't know how to do it with angular-jwt module. I dont' want the tokenGetter function to be executed for certain states (for example, login state)

Can someone give me a hint?

Thank you

**Comment by chenkie** [comment]
Hi @enricop89, the `tokenGetter` is executed when `$http` calls are made. Is there a call that gets made from your `/login` state when it loads? In any case, you'd want to apply `skipAuthorization` to the actual `$http` call, like this:

```js
$http({
  url: '/ping',
  skipAuthorization: true,
  method: 'GET'
});
```

Let me know if there's something else you're after :)
