### ISSUE TITLE
how to use angular-jwt 

### ISSUE THREAD

**Issue by med004** [auth0/angular-jwt#159]
Hello,
I am begining  in angular js , I generate token in backend but now I didn't khnow how to use angular-jwt to save token in localStorage and in interceptors 

help me for use angular-jwt and thanks

**Comment by chenkie** [comment]
Hi there,

This library is (mostly) just for sending a JWT as the `Authorization` header of an `$http` request. Saving the JWT in local storage is up to you :) Generally it's done after you send the user's credentials to your server and receive a JWT back.

Have you looked through the readme here?
