### ISSUE TITLE
UI Router 1.0.0 Fix

### ISSUE THREAD

**Issue by jasonmgeorge** [auth0/angular-jwt#161]
I am noticing that unauthenticatedRedirectPath no longer seems to trigger with the ui router transition code. If I force legacy state events unauthenticated redirect works with unauthenticatedRedirectPath and authManager.redirectWhenUnauthenticated(). 
https://ui-router.github.io/ng1/docs/latest/modules/ng1_state_events.html

Stepping through, it looks like the unauthenticated redirect is relying on loginPath and loginPath requires app state as opposed to a path.

**Comment by chenkie** [comment]
The library needs to be updated to support UI Router 1.0. It's in the backlog but no ETA yet unfortunately.

**Comment by 4O4** [comment]
Hi @chenkie Actually I submitted pull request for this some time ago (#155 )
I've been succesfully using my fork in production since then with angular-ui-router version ^1.0.3. It would be nice if you could merge / review my PR :)

**Comment by d3l33t** [comment]
please fix
