### ISSUE TITLE
how to increase     getTokenExpirationDate from 1 hour to 24 hours

### ISSUE THREAD

**Issue by constantinosergiou** [auth0/angular-jwt#162]
i am trying to increase the getTokenExpirationDate but it does not change 

  var d = new Date(86400000); // The 0 here is the key, which sets the date to the epoch
      d.setUTCSeconds(decoded.exp);

**Comment by fikoborquez** [comment]
Why do you want to do that? Remember that expiration date is a reserved claims from token's payload.
