### ISSUE TITLE
Token not added after refresh

### ISSUE THREAD

**Issue by spardo83** [auth0/angular-jwt#164]
After the token has refreshed  the api calls in flight end with 401, i´m using $resource to call server. 
here is my code
` if (options && options.url.substr(options.url.length - 5) == '.html') {
                        return null;
                    }

                    var token = authentication.getToken();

                    

                    if (token)
                        if (jwtHelper.isTokenExpired(token)) {
                            
                            var refreshToken = authentication.getRefresh();
                            return authentication.refreshToken(refreshToken).then(function (response) {
                                return response;
                            });
                        } else {
                            return token;
                        }`
 
Te token refresh returns 200 but te subsequent  calls made it before the token has been refreshed results in 401. May be i understend wrong but i think the api hangs the api calls and refresh token then make the rest of the calls?

**Comment by lerzenit** [comment]
Didn't try it but maybe your function to handle `authentication.refreshToken()` response should return `response.data.access_token` instead of `response`.
