### ISSUE TITLE
Documentation for using JwtHelperService

### ISSUE THREAD

**Issue by laran** [auth0/angular-jwt#166]
In angular2-jwt I was able to check to see whether the token was expired in a helper function called MyAuthService.isLoggedIn(). I haven't been able to figure out how to use the new JwtHelperService to do the same thing. It expects a config on creation and I'm not sure how to pull that through angular. Documentation would be very helpful. In the meantime I'll just check to see that the token exists.

FYI: I'm using Angular 5 and ^1.0.0-beta.9 of angular-jwt.

**Comment by Capitanbasa** [comment]
same here. i have same issue..

**Comment by LaMariluz** [comment]
Hi,
Here is my implementation. Hope it helps:

      let jwtHelperService = new JwtHelperService ({
        tokenGetter: () => {
          return localStorage.getItem('token');
        }
      });
I tried this (witch works) based on the basic usage in app.module:

    JwtModule.forRoot({
        config: {
          tokenGetter: () => {
            return localStorage.getItem('token');
          },
          whitelistedDomains: ['localhost:4200']
        }      
    })
