### ISSUE TITLE
urlBase64Decode issue

### ISSUE THREAD

**Issue by aresot** [auth0/angular-jwt#168]
Hi. We stumbled upon case when urlBase64Decode fails decoding valid token. when Im looking inside that function I see you using `return decodeURIComponent(escape(window.atob(r)))`. According to cods "escape" is deprecated and you should use encodeURIComponent instead. When I replaced escape with encodeURIComponent our problematic token was decoded correctly.

**Comment by timelf123** [comment]
This is still an issue
