### ISSUE TITLE
Angular 6.0.0 not supporting the Angular JWT

### ISSUE THREAD

**Issue by amith009** [auth0/angular-jwt#171]
Packages Json:
```
    @angular/animations": **"^6.0.0",**
    "@angular/cdk": **"^6.0.0",**
    "@angular/common": **"^6.0.0",**
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/material": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@auth0/angular-jwt": "^1.1.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "jwt-decode": "^2.2.0",
    "ngx-cookie-service": "^1.0.10",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
```

Log Error: 

ERROR in node_modules/@auth0/angular-jwt/src/jwt.interceptor.d.ts(3,10): error TS2305: Module '"C:/project/lawassito/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Comment by timfogarty-row8** [comment]
the issue is rxjs 6.0.  The owners of this module will need to

$ ng update @angular/cli
$ ng update @angular/core
$ ng update rxjs
$ npm i -g rxjs-tslint
$ rxjs-5-to-6-migrate -p src/tsconfig.app.json

**Comment by hesampour** [comment]
I get the following error:
  Package "@auth0/angular-jwt" has an incompatible peer dependency to "@angular/common" (requires "^4.4.6||^5.0.0", would install "6.0.0")

**Comment by chenkie** [comment]
This lib is actually for Angular 1. You're looking for http://github.com/auth0/angular2-jwt

**Comment by ShayMe21** [comment]
The naming of the packages can make you confused actually.

According to here (https://www.npmjs.com/package/@auth0/angular-jwt), you should be using `@auth0/angular-jwt` that supports **Angular6+**.

Please try with `npm install @auth0/angular-jwt` instead. I tested this earlier following the upgrade plan here (https://update.angular.io/) with the Angular2+ QuickStart SDK on Auth0 worked just fine.

**Comment by hesampour** [comment]
thanks alot.

**Comment by josuevalrob** [comment]
Is it in the master? should I update?

**Comment by ian4h** [comment]
It works but the package `rxjs-compat` is still required for backwards compatibility. Any idea when `rxjs-compat` can be removed?

`ERROR in node_modules/@auth0/angular-jwt/src/jwt.interceptor.d.ts(3,10): error TS2305: Module '"/home/ian/guru/guru-connect-client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.`

**Comment by amith009** [comment]
as per timfogarty-row8  and ian4h, look like we have to update the @auth0/angular-jwt?
do we have dates when we will get new version with above fixed?

**Comment by amith009** [comment]
Oho - I just saw the chenkie comment, I think he is right, SO I am closing this issue. 
Thanks chenkie.

**Comment by krushnachandra** [comment]
ERROR TypeError: Observable_1.Observable.defer is not a function
    at AuthHttp.push../node_modules/angular2-jwt/angular2-jwt.js.AuthHttp.request (angular2-jwt.js:140)
    at AuthHttp.push../node_modules/angular2-jwt/angular2-jwt.js.AuthHttp.requestHelper (angular2-jwt.js:104)
    at AuthHttp.push../node_modules/angular2-jwt/angular2-jwt.js.AuthHttp.get (angular2-jwt.js:151)


getting this error after updating to angular 6

**Comment by hesampour** [comment]
you are using angular2-jwt. change it to @auth0/angular-jwt.

**Comment by krushnachandra** [comment]
@hesampour thanks bro it worked after moving to @auth0/angular-jwt v2
