### ISSUE TITLE
--prod build.  Function expressions are not supported in decorators in 'ɵ0'

### ISSUE THREAD

**Issue by nickraphael** [auth0/angular-jwt#172]
I'm getting this error when I do an aot build.

ERROR in Error during template compile of 'LoginModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at src\app\components\login\login.module.ts(23,22)
      Consider changing the function expression into an exported function.

I suspect it's because I have a lambda in my module...
JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          return '';
        }
      }
    })

**Comment by chenkie** [comment]
This lib is actually for Angular 1. You're looking for http://github.com/auth0/angular2-jwt
