### ISSUE TITLE
SSR is failing window doesn't exist

### ISSUE THREAD

**Issue by jaumard** [auth0/angular-jwt#173]
Hello,

I trying to enable server side rendering on an existing project but it fail because of 

```
ReferenceError: window is not defined
    at Object.<anonymous> (/.../node_modules/@auth0/angular-jwt/bundles/core.umd.js:1:704)
```

I this module SSR ready ? Or did I miss something ?

**Comment by gabrieleciech** [comment]
This library is not designed for Angular 2+ but only for AngularJS. If you are using Angular 2+ please take a look at [https://github.com/auth0/angular2-jwt](https://github.com/auth0/angular2-jwt)

**Comment by jaumard** [comment]
Oups that's the one I use but I put issue on the wrong repo sorry :)
