### ISSUE TITLE
Interceptor can choke on undefined response

### ISSUE THREAD

**Issue by sithwarrior** [auth0/angular-jwt#184]
If you loose you internet connection, while a request is pending, the resulting response in the intercepter will be undefined, forcing an error on the status check.

I've created a small fix and submitted a pull request #183 

The issue can be reproduced by creating a network condition in google dev tools, with a long response time, starting a new token request, and switching to offline.

![screenshot 2019-01-04 at 14 43 15](https://user-images.githubusercontent.com/1550819/50769423-32df7880-1284-11e9-9c79-3cfd1c39c2e3.png)

**Comment by sithwarrior** [comment]
@luisrudge great that this got merged. Can we get it into a release, so its gets on NPM etc?

**Comment by luisrudge** [comment]
released on angular-jwt@0.1.11

**Comment by sithwarrior** [comment]
Sorry to keep bothering @luisrudge  But could you update the release tags here on github, as thats how Bower resolves versions. Right now `bower install angular-jwt` resolves 0.1.10 as thats the newest release version on github.

**Comment by luisrudge** [comment]
@sithwarrior no problem at all. Sorry to make you wait on this. This is an old package and the release process is not automated 😬 I just created the release on github!
