### ISSUE TITLE
Null Validation in isTokenExpired function

### ISSUE THREAD

**Issue by josuemma** [auth0/angular-jwt#19]
Hi

I think it could be a good idea to add a extra null validation in isTokenExpired function, something like :

 this.isTokenExpired = function(token) {
      if (!token) {
        return false;
         }  
      var d = this.getTokenExpirationDate(token);
      if (!d) {
        return false;
      }
      // Token expired?
      return !(d.valueOf() > new Date().valueOf());
    };

Regards

**Comment by mgonto** [comment]
Thanks for the comment :).

I don't know if that'd be correct, I think I'd rather return null or throw an exception :).

Are you up to doing a PR for this change?

Thanks!

**Comment by davisford** [comment]
Why are you doing this?

```javascript
var d = this.getTokenExpirationDate(token);
if (!d) {
  return false; 
}
```

If the token cannot be decoded and/or does not contain a valid `.exp` property wouldn't you assume either

1. it should be considered expired
2. or it should throw here

**Comment by smajl** [comment]
@josuemma Is that necessary? No, it is not. `getTokenExpirationDate()` function will return `null` and so the condition few lines further will return your desired `false`.
@davisford In my opinion a token without expiration date is life-time token (at least in client eyes).

**Comment by vitxd** [comment]
isn't it the case that isTokenExpired should actually be named "isTokenValid" as it returns true when is not expired?
