### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: this.tokenGetter is not a function

### ISSUE THREAD

**Issue by liyang010813** [auth0/angular-jwt#194]
![image](https://user-images.githubusercontent.com/31497640/77841067-b7d3ec00-71c0-11ea-9e07-da549579b4eb.png)
![image](https://user-images.githubusercontent.com/31497640/77841072-c9b58f00-71c0-11ea-8b16-cd55c7366c49.png)

**Comment by Sambego** [comment]
Hey @liyang010813, could you give me some more context? Perhaps some of the code where you implemented the `jwtOptionsProvider ` and `JwtInterceptor` .
