### ISSUE TITLE
How to skipAuthorization for ng-include or stateProvider template requests?

### ISSUE THREAD

**Issue by lopsided** [auth0/angular-jwt#27]
I noticed my app is trying to get a token when using the `ng-include` directive or using the `templateUrl` in `stateProvider`. Eg:

```
<ng-include src="'app/header/header.html'"></ng-include>
```
or
```
$stateProvider
    .state('home', {
                url: '/',
                controller: 'HomeCtrl',
                controllerAs: 'home',
                templateUrl: 'app/home/home.html'
            })
```

I can't see any way to skip the authorization for these requests, I'm probably not looking in the right place. Can anyone help?

Thanks

**Comment by mgonto** [comment]
This is certainly a bug :).

We'll take a look at it. However, it shouldn't be a problem for you since the template should load OK. Is it brining any problems to you?

Cheers!

**Comment by mgonto** [comment]
I've digged it and it's not really worth fixing it for the templates.

Closing for now.

I hope you don't mind.

Thanks again for the report!

**Comment by lopsided** [comment]
@mgonto I have had a little play and it looks like the problem is that we can't tell where the request actually came from in the http interceptor. All we have to go on is the url of the request. 

However I did spot that since the template load is waiting on the auth response it actually adds (relatively) a lot of time to the initial page load. So I thought of a workaround and wanted to see what your thoughts were on it. I've trimmed it to just the changes:

````
this.skipAuthForHtmlExts = false; // a master config switch to enable or disable this extra check
var config = this;
var isHtmlExtRequestToSkip = function(request) {
       return config.skipAuthForHtmlExts && request.url.substr(request.url.length - 5) == '.html';
};

....

return {
        request: function (request) {
            if (request.skipAuthorization || isHtmlExtRequestToSkip(request)) {
                return request;
            }
            ... etc ... 
````

If you like it I'm happy to submit a PR?

**Comment by mgonto** [comment]
Hey,

So I think in some cases it actually makes sense to send the Auth header to get the HTML.

What I'd do (and maybe it's just about documenting it), is that in the `tokenGetter` function, you inject the request config with `config` variable and then check there if it's an html.

Something like

```js
jwtInterceptorProvider.tokenGetter = function(store, config) {
  // Skip requests for HTMLs in my case
  if (request.url.substr(request.url.length - 5) == '.html') {
    return null;
  }

  return store.get('jwt');
}
```

What do you think about this aproach?

Cheers!

**Comment by lopsided** [comment]
I agree, it might make sense to sometimes to send the auth request. This looks like a good solution. I've tested it and it works perfectly. I've knocked up some documentation and submitted a PR. Let me know if you want me to change it at all. Cheers!

**Comment by mgonto** [comment]
Awesome :).

Just merged the PR.

Thanks for the help!

**Comment by yordis** [comment]
@mgonto is this fixed it?

**Comment by mgonto** [comment]
To fix it you just need to add some code to your `jwtInterceptorProvider.tokenGetter`. You don't really need to do anything else. Check out [this link](https://github.com/auth0/angular-jwt#not-sending-the-jwt-for-template-requests).

Cheers!

**Comment by sakopov** [comment]
This doesn't seem to work. I have index.html with a templated directive. The template is failing to load even with the conditional check for .html extension.
