### ISSUE TITLE
Bower install doesn't return the 0.0.6 version

### ISSUE THREAD

**Issue by mica16** [auth0/angular-jwt#36]
Is the version 0.0.6 already on bower registry?

When I install it, I keep getting the 0.0.4 version.

Thanks a lot.

**Comment by mgonto** [comment]
Hey,

It should be. `bower.json` has the correct version on it.

Haven’t you specified version somewhere?

Cheers!

—
var signature = { 
  name: "Martin Gontovnikas",  
  title: "Software Engineer",  
  twitter: "twitter/mgonto",
  github: "github/mgonto",
  linkedin: "linkedin/mgonto"
};

On 2 de abril de 2015 at 16:05:51, Michael AZERHAD (notifications@github.com) wrote:

Is the version 0.0.6 already on bower registry?

When I install it, I keep getting the 0.0.4 version.

Thanks a lot.

**Comment by mica16** [comment]
Hi,

I merely executed ```bower install angular-jwt``` the first time.

I also tried to specify this in my bower.json: 

"dependencies": {
    "angular-jwt": "0.0.6"
  } 

with a ```bower cache clean``` and then ```bower install angular-jwt```
but I keep have this: 
```
mismatch Version declared in the json (0.0.4) is different than the resolved one (0.0.6)
```

**Comment by mgonto** [comment]
I’l try it out.

—
var signature = { 
  name: "Martin Gontovnikas",  
  title: "Software Engineer",  
  twitter: "twitter/mgonto",
  github: "github/mgonto",
  linkedin: "linkedin/mgonto"
};

On 2 de abril de 2015 at 16:18:21, Michael AZERHAD (notifications@github.com) wrote:

Hi,

I merely executed bower install angular-jwt the first time.

I also tried to specify this in my bower.json:

"dependencies": {
"angular-jwt": "0.0.6"
}

with a bower cache clean and then bower install angular-jwt
but I keep have this:

mismatch Version declared in the json (0.0.4) is different than the resolved one (0.0.6)

**Comment by mattsmith-au** [comment]
Looks like the angular-jwt version in the 0.0.6 tag is still set to "0.0.4". Hope that helps?

```
{
  "name": "angular-jwt",
  "version": "0.0.4",
  ...
}
```

**Comment by mgonto** [comment]
Published 0.0.7 fixed now :).

Let me know if it works.

Cheers!

—
var signature = { 
  name: "Martin Gontovnikas",  
  title: "Software Engineer",  
  twitter: "twitter/mgonto",
  github: "github/mgonto",
  linkedin: "linkedin/mgonto"
};

On 6 de abril de 2015 at 21:10:59, mattsmith-au (notifications@github.com) wrote:

Looks like the angular-jwt version in the 0.0.6 tag is still set to "0.0.4". Hope that helps?

{
  "name": "angular-jwt",
  "version": "0.0.4",
  ...
}

**Comment by mica16** [comment]
Now it works :) What was the problem ?

Thanks a lot !

**Comment by mgonto** [comment]
That I forgot to update bower.json, but I did update the package.json.

Thanks!
