### ISSUE TITLE
Cannot send requests with angular-jwt in IE9

### ISSUE THREAD

**Issue by ramsaylee** [auth0/angular-jwt#37]
Hi,
First of all, thanks for this great module, it helps me a lot!

I have an issue here, this module works great in FF/Chrome, but when I want to test my app in IE9(I did not tried other IE versions), it is not working any more! The IE Dev tool showed that only requests with "skipAuthorization: true" can be sent and respond the correct response, while requests without "skipAuthorization: true" cannot even be sent. 
I have checked that the token has been saved to localStorage correctly.

AngularJS 1.2.26
angular-jwt The latest version
IE9

Could you please help me with this? Thanks in advance!

**Comment by tedvanderveen** [comment]
+1 sounds like a similar problem we're having here

**Comment by mgonto** [comment]
Unfortunately, I don't have any IE to debug (nor windows :(). Could you help me out with it? Where is it failling if you debug the code?

Thanks for the report!

**Comment by ramsaylee** [comment]
@mgonto Actually I did debug the code but got nothing. It just didn't send requests with angular-jwt. I also did some research and got nothing neither. I doute that this is not a problem of angular-jwt, maybe IE8/9 have problems with custom http header.

Is there any way I can do to send token not in the header but in the query string?

Thanks!

**Comment by alexbokii** [comment]
Hi guys! I have the same issue - an error in IE9. Console says "Object doesn't support this property or method 'atob' "
IE9 doesn't support the method atob() (support IE10+)
If someone knows how to fix this issue can you share it please?

**Comment by peteringram0** [comment]
Line number 75 on angular-jwt.js is causing the IE9 issues.

```
return decodeURIComponent(escape(window.atob(output)));
```

As per W3School .atob is only supported on IE10 +
http://www.w3schools.com/jsref/met_win_atob.asp

**Comment by mgonto** [comment]
Thanks for the mentions.

Is anybody up for a PR to fix this :)?

Thanks!

**Comment by MCKmecik** [comment]
Hi guys,
has anybody solved this problem?

Thanks.

**Comment by mecapetr** [comment]
I have solved this with base64.js 
https://github.com/client9/stringencoders/tree/master/javascript

I have Included the base64.js and then in angular-jwt service called "jwtHelper" I have replaced "windows.atob" to "base64.decode".

**Comment by mgonto** [comment]
Thanks for the comment with the fix.

Closing!
