### ISSUE TITLE
support for typescript

### ISSUE THREAD

**Issue by frankitoy** [auth0/angular-jwt#40]
Hi,

Is there any existing .d.ts for ambient declarations? Thanks.

**Comment by mgonto** [comment]
Hey,

We didn’t made any, but one may exist. Please check on the DefinetlyTyped repository.

Thanks!

—
var signature = { 
  name: "Martin Gontovnikas",  
  title: "Software Engineer",  
  twitter: "twitter/mgonto",
  github: "github/mgonto",
  linkedin: "linkedin/mgonto"
};

On 15 de abril de 2015 at 23:25:24, Frank (notifications@github.com) wrote:

Hi,

Is there any existing .d.ts for ambient declarations? Thanks.

**Comment by frankitoy** [comment]
Hi Martin,

I did try to look at DefinitelyTyped repo also phrases pertaining to jwt but to no avail I did not find any.

**Comment by chenkie** [comment]
There's one in DefinitelyTyped now :) https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/angular-jwt
