### ISSUE TITLE
Add support for nbf(not before) during token validity check

### ISSUE THREAD

**Issue by leesdolphin** [auth0/angular-jwt#42]
Hi,

Are there any plans to add support for the `nbf` claim when checking if the token in valid. From my understanding of the [specification](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.5) if the claim exists then the token is only valid if the current time is after the time given(with a few minutes leeway to account for clocks that are slightly off). 

I am more than happy to implement this if it going to be helpful for others.

**Comment by mgonto** [comment]
Hey,

Thanks for the issue :). Please do send a PR with this feature :).

Thanks!
