### ISSUE TITLE
Unable to use angular-jwt with AppGyver Supersonic

### ISSUE THREAD

**Issue by NomNomCameron** [auth0/angular-jwt#43]
AppGyver's Supersonic uses bower out of the box, after installing the bower package I am attempting to inject `angular-jwt` into my `AuthService` but I am getting an `$injector` issue as it can't find this module?

I've also tried just including the script tag that links to cdnjs in the layout to no avail.

Probably not an angular-jwt issue perse but I thought I'd open an issue to attempt to get some help!

I would really appreciate it!

**Comment by NomNomCameron** [comment]
I was able to figure this issue out and it is nothing wrong with `angular-jwt`

I thought that supersonic would create a script tag for each component that you install with bower in the layout.html file, but it does not, after properly including that and injecting a service from `angular-jwt` I am now able to use it. SWEET!

Thank you guys so much for making this handy library!

**Comment by mgonto** [comment]
I'm glad it worked :).

Cheers!
