### ISSUE TITLE
angular-jwt on client side does not decode flask-jwt tokens from server side

### ISSUE THREAD

**Issue by hussaintamboli** [auth0/angular-jwt#48]
I am using Flask as a back end (api) and angularjs as a front end. For JWTs I am using Flask-JWT in my api. And I was trying to configure angular-jwt in my front end

On login, I call /api/v1/auth from angularjs app and I get the token. e.g. 

     eyJhbGciOiJIUzI1NiIsImV4cCI6MTQzMjExNTAzMiwiaWF0IjoxNDMyMTE1MDAyfQ.eyJ1c2VyX2lkIjoxfQ.dmwvvgDinqWojmZ9ff1wHk_gDYM-dXNG-uTrabY9fFM

Then I store it in `localStorage`

    localStorage['id_token'] = data.token;

But when I try to decode it in another part of my app, I get `null`

    console.log('token expiration date', jwtHelper.getTokenExpirationDate(localStorage.getItem('id_token')));
    console.log('token expired', jwtHelper.isTokenExpired(localStorage.getItem('id_token')));

Note that the algorithms that I have tried in back end are

    bcrypt, sha512_crypt, or pbkdf2_sha512
    // SECURITY_PASSWORD_HASH from https://pythonhosted.org/Flask-Security/configuration.html

Why doesn't it work?

In fact I see it getting decoded in http://jwt.io/

**Comment by mgonto** [comment]
There was a bug in the decoding. Now works as of 0.0.9 :). 

Thanks!
