### ISSUE TITLE
Support for changing the authorization prefix.

### ISSUE THREAD

**Issue by negletios** [auth0/angular-jwt#49]
Hello and congrats on the library.

I would recommend to add a config function so I can change the Authorization prefix.

By default all the Requests are being send with the prefix: Authorization: Bearer [Token] 

In my case, I must send it with Authorization: JWT [Token].

I can change it by modifying the library itself (this.authPrefix = 'Bearer '; ) but it would be nice If I could do it straight from my code. 

Thanks.

**Comment by mikedon** [comment]
I need this as well on my project.  If the owners think this is a good feature to have then I don't mind working on a pull request

**Comment by Wicked0ne** [comment]
I just ran into this issue myself. I would love a option to change the prefix as well. negletios is it just that one line that needs to be changed?

**Comment by DinoRatcliffe** [comment]
It looks like the line
```JavaScript 
this.authPrefix = 'Bearer ';
``` 
was purposefully made accessible so that you can change it in your code using:

```JavaScript
jwtInterceptorProvider.authPrefix = 'JWT ';
```

**Comment by negletios** [comment]
Hello @DinoRatcliffe,

Thanks for your response.

**Comment by leonsas** [comment]
+1

**Comment by TheSharpieOne** [comment]
You can
```
angular.module('app', ['angular-jwt'])
  .config(function Config(jwtInterceptorProvider) {
    // jwtInterceptorProvider.urlParam = "myCustomParam";
    // - or -
    jwtInterceptorProvider.authHeader = 'X-My-Custom-Header';
    jwtInterceptorProvider.authPrefix = 'MyCustomPrefix';

    jwtInterceptorProvider.tokenGetter = function (jwtHelper, config) {
        \\...
    };
    \\....
  });
```

@mgonto This can probably be closed.

**Comment by iannyanes** [comment]
@ntotten This ticket looks like it could be closed.
