### ISSUE TITLE
support CORS option ?

### ISSUE THREAD

**Issue by axacheng** [auth0/angular-jwt#55]
Hi experts !

I really love angular-jwt and use it for my production projects. It runs so good until I have CORS issue.
I need to use interceptor for every get/post/put requests, but it also causes the CORS issue....

The url I browse is : https://axa.mydomain.com and my angularjs api is calling Google App Engine cloud endpoint which is https://axa-prod.appspot.com/_ah/api/v5/xxxxxx this request would trigger CORS issue due to interceptor force to append 'Authentication'  header? (Correct me if i'm wrong.)

I've tried to confiig $httpProvider in app.js  , but didn't get luck!

``` js
  delete $httpProvider.defaults.headers.common['X-Requested-With'];
  $httpProvider.defaults.withCredentials = true;
  $httpProvider.defaults.useXDomain = true;
```

Anyone have better suggestions to solve this CORS issue? Thanks!

![1](https://cloud.githubusercontent.com/assets/5593412/9846644/11e3068a-5b06-11e5-8fd7-79d3282e3545.png)

 Below is my angularjs code for interceptor

``` js
.config(function Config($httpProvider, jwtInterceptorProvider) {
  jwtInterceptorProvider.tokenGetter = function() {
    var access_key = localStorage.getItem('access_key');
    //console.log(access_key)
    return access_key
  }
  $httpProvider.interceptors.push('jwtInterceptor');
})
```

**Comment by Shimmi** [comment]
Hi @axacheng,
Hope you have been already able to solve this issue as it is quite old, but let me answer it as it is still open.

Enabling CORS support must be done on the server side. It is driven by `Access-Control-Allow-Origin` http header. I Googled for you something that might help you: http://enable-cors.org/server_appengine.html

But do not use `*` as it allows requests from all domains. You should always specify only the domain you really want to allow requests from.

**Comment by chenkie** [comment]
Thanks for your answer @Shimmi :) Closing as I think this covers it.
