### ISSUE TITLE
Any chance of getting a react-jwt?

### ISSUE THREAD

**Issue by rhblind** [auth0/angular-jwt#56]
Hi,
Thank for this module, I've been using it for several angular projects.
Now, I'm about to start a react-native app (using Reflux) and I'm library shopping a bit. I'm currently working on the authentication mechanisms, and was kind of hoping to be able to port my angular authentication services to Reflux pattern, but can't seem to find a jwt token library with all the goodies like in this (like checking if the token is expired, getting the expiration date, validity and so on).

So, is there any chance of seing a react port of this library?
Thanks!

**Comment by chenkie** [comment]
There's a possibility of this and there may in fact be some packages out there already which handle it :)
