### ISSUE TITLE
question: any interceptor to enqueue requests if token expired?

### ISSUE THREAD

**Issue by apneadiving** [auth0/angular-jwt#6]
Hi,

I wonder if you implemented an auto refresh for the token:
- request made
- fails because token expired
- triggers a refresh token request
- all requests being made until the fresh token is retrieved being enqueued

Thanks,

Benjamin

**Comment by sirago** [comment]
Is there an example using a promise anywhere? I'm running into the situation where my I'm hitting the refresh endpoint 3x for multiple calls that fire at the same time.
