### ISSUE TITLE
jwtInterceptor - tokenGetter is not called because of angular caching

### ISSUE THREAD

**Issue by RayzRazko** [auth0/angular-jwt#60]
Hi guys. I noticed that sometimes tokenGetter is not called during request and instead of sending refresh token request to fetch updated access token, interceptor just do nothing. As I understand angular caches headers and because of next lines the tokenGetter is not called:

``` javascript
request.headers = request.headers || {};
// Already has an Authorization header
if (request.headers[config.authHeader]) {
    return request;
}
```

Maybe it will be better to add configurable parameter, something like "forceHearedUpdate" and if this parameter is true then omit the `if (request.headers[config.authHeader])` branch of code.

**Comment by windom** [comment]
Hi. I've noticed this too, but it happens in a very random fashion. Do you know any concrete methods to reproduce this? When does Angular cache the headers?

**Comment by RayzRazko** [comment]
It's hard to define steps, but it happens really often.

**Comment by windom** [comment]
You could be right, by removing the header check the issue seemed to vanish. But it's strange nonetheless.

**Comment by windom** [comment]
I take back everything. My issue was different: in the tokenGetter method I checked if the token has expired and only then did I call the refresh API method. When the client clock and the server clock weren't in sync it could happen, that the client sees an expired token as valid and would not call the refresh method.

**Comment by tlkahn** [comment]
Hi, maybe I am a bit late to the party. Is the issue solved now? Does adding a random string to the end of the URL help?
