### ISSUE TITLE
$http.jsonp token not in header

### ISSUE THREAD

**Issue by kahwooi** [auth0/angular-jwt#62]
I am trying to use angular-jwt in `service` but it does not append authorization on http call, can it be use with `$http.jsonp`:

``` angular.module('TestApp')
  .config(function Config($httpProvider, jwtInterceptorProvider) {
    jwtInterceptorProvider.tokenGetter = ['merchantService', function(merchantService) {
        merchantService.doSomething();
        return localStorage.getItem('token');
    }];

    $httpProvider.interceptors.push('jwtInterceptor');
  })
  .service('Merchant', ['$http', function($http) {
    var baseUrl = "http://test.com";

    return {
        terminal: function(success, error) {
            $http.jsonp(baseUrl + '/tests?callback=jsonp_callback').success(success).error(error)
        }
    } 
  }]);
```

If I am using $http call, I get this error:

`No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Can this be the reason?

**Comment by Shimmi** [comment]
Hi @kahwooi,
The `No 'Access-Control-Allow-Origin' header is present on the requested resource.` can be definitely the reason why it fails. Seems you are running into CORS issue. You have to allow the CORS by adding the `Access-Control-Allow-Origin` header with the domain you are making the requests from.

**Comment by chenkie** [comment]
Thanks for your suggestion here @Shimmi :) Closing as I think that covers it.

**Comment by onigetoc** [comment]
This really suck, and if you do not own the domain?
like itunes search api ?????
It's working with jQuery with no problem
