### ISSUE TITLE
Flexible authPrefix value

### ISSUE THREAD

**Issue by awwester** [auth0/angular-jwt#63]
I would like to change the authPrefix from "Bearer " to "JWT ". I'm not seeing anything in docs or source code saying that's possible. Is that currently possible (maybe I'm missing it?) and/or are there plans of allowing flexibility for the authPrefix?

**Comment by mrzmyr** [comment]
This should work:
```js
.config(function($httpProvider, jwtInterceptorProvider) {
  jwtInterceptorProvider.authPrefix = 'JWT';
})
```
