### ISSUE TITLE
Support for compression algorithms

### ISSUE THREAD

**Issue by lucastschmidt** [auth0/angular-jwt#66]
Hey guys, is there a way to automatically support DEFLATE or any other algorithm?

In theory, we can always get the token, process and then send it to the library so it can detect if expired or not and all those things. 

Is there a good way to do this? If there was a method we could override would be nice, or some interceptor. 

Thanks!

**Comment by chenkie** [comment]
This would be outside the scope of this library I think. The processing could definitely be done in the `tokenGetter` :)
