### ISSUE TITLE
Does it require auth0

### ISSUE THREAD

**Issue by NickAb** [auth0/angular-jwt#68]
Does this library works with auth0 only or it can be used with on-premise ADFS without auth0?

**Comment by Shimmi** [comment]
Hi @NickAb,
This library serves only as a client library to handle JWT tokens (parsing, getting expiration date, ...).
It can work with any backend that is configured to populate JWT authentication tokens.

I am not familiar with AD FS, but from a quick google search there seems to be some support for JWT in AD FS. Try googling `ADFS JWT`

**Comment by NickAb** [comment]
Thank you. Indeed ADFS support JWT and some of the oauth flows.
I just wanted to make sure if this library is generic and not auth0 specific, because references to auth0 at the end of readme got me confused.
Thanks again.
