### ISSUE TITLE
Angular jwt cannot decode token from Laravel backend

### ISSUE THREAD

**Issue by mudin3i** [auth0/angular-jwt#79]
Hello!

Thanks for the jwt helper for angular.
It is very awesome, and easy to use.
It is first time I am using JWT based auth.
After login, laravel backend is sending me a token.
I am using jwtHelper to decode, I can only get url, not username,...
Is it normal?

Thanks

**Comment by chenkie** [comment]
You would need to check the token you get back from your Laravel backend to see if it has that information in the payload :) You can try decoding it at jwt.io
