### ISSUE TITLE
unauthenticatedRedirector Error

### ISSUE THREAD

**Issue by douglaszaltron** [auth0/angular-jwt#87]
jwtOptionsProvider.config({
      tokenGetter: ['store', function (store) {
        return store.get('access_token');
      }],
      whiteListedDomains: ['api.servidor.com', 'localhost'],
      unauthenticatedRedirector: ['$state', function ($state) {
        $state.go('login');
      }]
    });

exception:

config.unauthenticatedRedirector is not a function. (In 'config.unauthenticatedRedirector($location)', 'config.unauthenticatedRedirector' is an instance of Array)
column: 45
line: 260
message: "config.unauthenticatedRedirector is not a function. (In 'config.unauthenticatedRedirector($location)', 'config.unauthenticatedRedirector…"

**Comment by chenkie** [comment]
Are your other options working if you remove the `unauthenticatedRedirector`?

**Comment by douglaszaltron** [comment]
yes! working.

**Comment by chenkie** [comment]
@douglaszaltron give it a shot now and let me know :)
