### ISSUE TITLE
authmanager is polluting $rootScope

### ISSUE THREAD

**Issue by IagoLast** [auth0/angular-jwt#90]
``` javascript
$rootScope.isAuthenticated = false;
```

It’s a bad idea to attach too much logic to this global context, in the same way that it’s not a good idea to dirty the JavaScript global scope.

Instead, authManager should have an **isAuthenticated** property that can be used from anywhere.

``` javascript
// ...
     var isAuthenticated = false;

      function authenticate() {
        isAuthenticated = true;
      }

      function unauthenticate() {
        isAuthenticated = false;
      }
// ...

return {
// ...
    isAuthenticated : isAuthenticated,
}
```

https://www.thinkingmedia.ca/2015/01/learn-how-to-use-scopes-properly-in-angularjs/

**Comment by motin** [comment]
100% agree. Using $rootScope is also not best practice with 1.5+ components that has isolated scopes. Using authManager.isAuthenticated is good practice with components.

**Comment by motin** [comment]
Remember that there is a confusing method called "isAuthenticated()" that needs to be renamed first (preferably to something like idTokenIsNotExpired())

**Comment by motin** [comment]
Suggestion: Instead of setting a property on $rootScope, broadcast 'authManager.authenticated' and 'authManager.unauthenticated' instead.
