### ISSUE TITLE
unable to install angular-jwt with bower

### ISSUE THREAD

**Issue by jeff-li** [auth0/angular-jwt#93]
tried to run 
`bower install --save angular-jwt`

I got this error message:
`$ bower install --save angular-jwt
bower angular-jwt#*             cached https://github.com/auth0/angular-jwt.git#0.1.3
bower angular-jwt#*           validate 0.1.3 against https://github.com/auth0/angular-jwt.git#*
bower                        ECONFLICT Unable to find suitable version for angular-jwt
`
I'm currently using Angular 1.5.8

**Comment by chenkie** [comment]
Can you try `bower cache clean`?
