### ISSUE TITLE
jwtOptions.tokenGetter returning null value

### ISSUE THREAD

**Issue by nlaw86** [auth0/angular-jwt#95]
When trying to use the tokenGetter method in authManager.checkAuthOnRefresh I kept getting a null value instead of a token when one should be present.

Looking at the code, I can see that the jwtOptions.tokenGetter function definition just returns a null value, and I can't see anywhere where this is changed due to context:

```
tokenGetter: function() {
  return null;
}
```

If I change the function definition to:

```
tokenGetter: function() {
  return localStorage.getItem('id_token');
} 
```

It all seems to work OK.

Please forgive me if I've missed something obvious here (more than likely!!).

Thank you.

**Comment by chenkie** [comment]
The idea is to change the `tokenGetter` to be whatever you need :) Different apps have different ways of storing tokens, and with different identifiers. So defining your `tokenGetter` in your `jwtOptionsProvider.config` is the right approach here.

**Comment by nlaw86** [comment]
Thank you! That makes total sense, sorry for raising it as an issue. Thanks again for your help.

**Comment by nlaw86** [comment]
I'm sorry if this is a naive question, but is there a global way to change these settings across the app, without touching the source code of the package? Thanks again!
