### ISSUE TITLE
Fire an event after authentication check

### ISSUE THREAD

**Issue by knation** [auth0/angular-jwt#98]
Right now, `$rootScope.isAuthenticated` defaults to false, which means that, on page load, there's no way to know if the user is actually authenticated or not. The only way would be to wait an arbitrary amount of time to see if `$rootScope.isAuthenticated` changes to true.

In my case, I want to show the lock right away when the screen loads if the user is not logged in, but the way it is now, it will _always_ show since `$rootScope.isAuthenticated` defaults to false.

There should be some `authenticationChecked` event that fires after the check is done, so you can do something like this:

```
// Block UI while we wait to see if user is authenticated...

$rootScope.$on('authenticationChecked', function(isAuthenticated) {
  if (isAuthenticated) {
    // Unblock UI
  } else {
    authService.login();
  }
});
```

**Comment by kshaaban-** [comment]
There is a way to check authentication on page refresh, [check the relevant section in the readme file](https://github.com/auth0/angular-jwt#getting-authentication-state-on-page-refresh).

Be mindful that this will not work if your `tokenGetter` method relies on checking the $http request's configuration before returning a token. Issue #92 reports that though, and it should be fixed eventually :)

**Comment by knation** [comment]
Thanks @kshaaban- that part's working great. It's when the page actually refreshes that you're not able to check the state in controllers. I found a work-around...just checking if `authService.user_id` exists. I'm not sure how reliable this is, though, since it's set before `$rootScope.isAuthenticated` is actually set.

**Comment by kshaaban-** [comment]
I may have misunderstood the issue earlier; seems like indeed there should be a way to notify the app that authentication status has been checked.

You could wrap logic in your controller's code in a `$timeout` function, which would trigger a digest cycle `$rootScope.isAuthenticated` value.

Assuming your `tokenGetter` is returning a valid token **AND** your `authManager` is checking auth on refresh:
```javascript
app.controller('testCtrl', function($timeout, $rootScope) {
    console.log($rootScope.isAuthenticated); // It would be false here
    $timeout(function() {
        console.log($rootScope.isAuthenticated); // But would be true here
    });
});
```

**Comment by knation** [comment]
That seems to work, as long as it's in the controller. Trying the same thing in `app.run` does not, however, which makes sense I suppose. So I had to create a master controller just for the sake of handling this case.

Thanks!
