### ISSUE TITLE
ReferenceError: Can't find variable: require   at node_modules/angular2-jwt/angular2-jwt.js:16

### ISSUE THREAD

**Issue by ovione** [auth0/angular-jwt#99]
I have an angular2 version 2.0 application wheer some services depend on the angular2-jwt.js.
When I run my tests I get 
`ReferenceError: Can't find variable: require   at node_modules/angular2-jwt/angular2-jwt.js:16`

My KArma.conf.js has the following files
    files: [
      'node_modules/core-js/client/shim.min.js',
      'node_modules/zone.js/dist/zone.js',
      'node_modules/zone.js/dist/long-stack-trace-zone.js',
      'node_modules/zone.js/dist/proxy.js',
      'node_modules/zone.js/dist/sync-test.js',
      'node_modules/zone.js/dist/jasmine-patch.js',
      'node_modules/zone.js/dist/async-test.js',
      'node_modules/zone.js/dist/fake-async-test.js',
      'node_modules/systemjs/dist/system.src.js',
      'node_modules/moment/moment.js',
      'node_modules/reflect-metadata/Reflect.js',
      'node_modules/angular2-jwt/angular2-jwt.js'
    ],

I use SystemJS to load the artifacts.

Should I include somethinng else in the karma or is the error comming from the way angular2-jwt.js is compiled maybe?

thanks for your help

**Comment by chenkie** [comment]
Can you share your `system.config.js`?

**Comment by chenkie** [comment]
Can you move this issue over to https://github.com/auth0/angular2-jwt ? This repo is for Angular 1.x :)
